name: build-and-deploy

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

env:
  cache-name: brechtserckx-be
  pages-branch: github-pages
  pages-folder: _site

jobs:

  #########
  # Build #
  #########

  build-and-cache:
    name: Build and cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
          submodules: true

      - name: Install Nix
        uses: cachix/install-nix-action@v19

      - name: Test Nix install
        run: nix-build --version

      - uses: cachix/cachix-action@v12
        with:
          name: '${{ env.cache-name }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: 'iohk'

      - name: Build site with Nix
        run: nix build '.?submodules=1'

      - name: Deploy site
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: ${{ env.pages-branch }}
          folder: result
